---

- name: Start OpenSCAP Vulnerability check
#  shell: oscap xccdf eval --tailoring-file /tmp/tailoring-xccdf.xml --results /tmp/results.xml --report /tmp/report.html --profile cis_digit /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
  shell: oscap oval eval --report /tmp/vulnerability.html --results /tmp/vulnerability.xml /tmp/rhel-8.oval.xml
  ignore_errors: yes

- name: Copy the Vulnerability report back to localhost
  fetch:
     src: /tmp/vulnerability.html
     dest: "{{ vulnDir }}/{{ inventory_hostname }}_Vulnerability_{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}_report.html"
     flat: yes

- name: Copy the Vulnerability results back to localhost
  fetch:
     src: /tmp/vulnerability.xml
     dest: "{{ vulnDir }}/{{ inventory_hostname }}_Vulnerability_{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}_results.xml"
     flat: yes
